insert into drinks (drinks_id, item, temperature) values (1, 'Betty White Frappucino', 66);
insert into drinks (drinks_id, item, temperature) values (2, 'Cinnamon Toast Crunch Latte', 117);
insert into drinks (drinks_id, item, temperature) values (3, 'Fear Street Frappucino', 44);
insert into drinks (drinks_id, item, temperature) values (4, 'Chocolate-Covered Strawberry Drink', 101);
insert into drinks (drinks_id, item, temperature) values (5, 'Pumpkin Pie Frappuccino', 91);
insert into drinks (drinks_id, item, temperature) values (6, 'Orange Drink', 48);
insert into drinks (drinks_id, item, temperature) values (7, 'Candy Corn Frappuccino', 33);
insert into drinks (drinks_id, item, temperature) values (8, 'French Toast Frappuccino', 66);
insert into drinks (drinks_id, item, temperature) values (9, 'Candy Corn Frappuccino', 26);
insert into drinks (drinks_id, item, temperature) values (10, 'Blackberry Caramel Macchiato', 113);
insert into drinks (drinks_id, item, temperature) values (11, 'Cotton Candy Frappuccino', 75);
insert into drinks (drinks_id, item, temperature) values (12, 'Apple Martini Refresher', 38);
insert into drinks (drinks_id, item, temperature) values (13, 'Caribbean Refresher', 56);
insert into drinks (drinks_id, item, temperature) values (14, 'Key Lime Pie Refresher', 53);
insert into drinks (drinks_id, item, temperature) values (15, 'Cookies and Cream Cold Brew', 21);
insert into drinks (drinks_id, item, temperature) values (16, 'Orange Drink', 46);
insert into drinks (drinks_id, item, temperature) values (17, 'Orange Drink', 27);
insert into drinks (drinks_id, item, temperature) values (18, 'The Medicine Ball', 85);
insert into drinks (drinks_id, item, temperature) values (19, 'Love Bug Frappuccino', 105);
insert into drinks (drinks_id, item, temperature) values (20, 'Golden Girls Frappuccino', 33);
insert into drinks (drinks_id, item, temperature) values (21, 'Purple Drink', 101);
insert into drinks (drinks_id, item, temperature) values (22, 'Harry Potter Pumpkin Juice', 30);
insert into drinks (drinks_id, item, temperature) values (23, 'Betty White Frappucino', 105);
insert into drinks (drinks_id, item, temperature) values (24, 'Strawberries and Cream Refresher', 100);
insert into drinks (drinks_id, item, temperature) values (25, 'Dole Whip Frappuccino', 54);
insert into drinks (drinks_id, item, temperature) values (26, 'Betty White Frappucino', 56);
insert into drinks (drinks_id, item, temperature) values (27, 'Minnie Mouse Frappuccino', 110);
insert into drinks (drinks_id, item, temperature) values (28, 'Key Lime Pie Refresher', 51);
insert into drinks (drinks_id, item, temperature) values (29, 'Betty White Frappucino', 97);
insert into drinks (drinks_id, item, temperature) values (30, 'Betty White Frappucino', 62);
insert into drinks (drinks_id, item, temperature) values (31, 'Key Lime Pie Refresher', 65);
insert into drinks (drinks_id, item, temperature) values (32, 'Dirty Chai Latte', 95);
insert into drinks (drinks_id, item, temperature) values (33, 'Raspberry Cheesecake Frappuccino', 74);
insert into drinks (drinks_id, item, temperature) values (34, 'Orange Dreamsicle Float', 62);
insert into drinks (drinks_id, item, temperature) values (35, 'Baby Yoda Frappuccino', 102);
insert into drinks (drinks_id, item, temperature) values (36, 'Honey Peach Freeze', 77);
insert into drinks (drinks_id, item, temperature) values (37, 'Layered Lemonade', 117);
insert into drinks (drinks_id, item, temperature) values (38, 'Tiramisu Frappuccino', 60);
insert into drinks (drinks_id, item, temperature) values (39, 'Strawberries and Cream Refresher', 94);
insert into drinks (drinks_id, item, temperature) values (40, 'Team Jacob Frappucino', 67);
insert into drinks (drinks_id, item, temperature) values (41, 'Strawberries and Cream Refresher', 37);
insert into drinks (drinks_id, item, temperature) values (42, 'Fear Street Frappucino', 83);
insert into drinks (drinks_id, item, temperature) values (43, 'Orange Lemon Smoothie ', 64);
insert into drinks (drinks_id, item, temperature) values (44, 'Love Bug Frappuccino', 51);
insert into drinks (drinks_id, item, temperature) values (45, 'Hocus Pocus Latte', 40);
insert into drinks (drinks_id, item, temperature) values (46, 'Chocolate-Covered Strawberry Drink', 54);
insert into drinks (drinks_id, item, temperature) values (47, 'Shortbread Cookie Frappuccino', 94);
insert into drinks (drinks_id, item, temperature) values (48, 'Cotton Candy Frappuccino', 54);
insert into drinks (drinks_id, item, temperature) values (49, 'Hocus Pocus Latte', 20);
insert into drinks (drinks_id, item, temperature) values (50, 'Shortbread Cookie Frappuccino', 62);
insert into drinks (drinks_id, item, temperature) values (51, 'Candy Corn Frappuccino', 113);
insert into drinks (drinks_id, item, temperature) values (52, 'Dirty Chai Latte', 108);
insert into drinks (drinks_id, item, temperature) values (53, 'Winnie-the-Pooh Frappuccino', 101);
insert into drinks (drinks_id, item, temperature) values (54, 'French Toast Frappuccino', 60);
