insert into food (food_id, variety, expiration_date, refridgerated) values (1, 'Tomato & Mozzarella on Focaccia', '23.05.2021', false);
insert into food (food_id, variety, expiration_date, refridgerated) values (2, 'Cheddar & Uncured Salami Protein Box', '02.01.2022', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (3, 'Cheese Trio Protein Box', '31.01.2022', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (4, 'Ham & Swiss on Baguette', '06.04.2021', false);
insert into food (food_id, variety, expiration_date, refridgerated) values (5, 'Cheese Trio Protein Box', '11.03.2021', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (6, 'PB&J Protein Box', '01.11.2021', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (7, 'Cheese Trio Protein Box', '17.07.2021', false);
insert into food (food_id, variety, expiration_date, refridgerated) values (8, 'Chickpea Bites & Avocado Protein Box', '09.05.2021', false);
insert into food (food_id, variety, expiration_date, refridgerated) values (9, 'Tomato & Mozzarella on Focaccia', '06.07.2021', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (10, 'Chicken & Hummus Protein Box', '25.08.2021', false);
insert into food (food_id, variety, expiration_date, refridgerated) values (11, 'Tomato & Mozzarella on Focaccia', '13.06.2021', false);
insert into food (food_id, variety, expiration_date, refridgerated) values (12, 'Avocado Spread', '21.05.2021', false);
insert into food (food_id, variety, expiration_date, refridgerated) values (13, 'Chickpea Bites & Avocado Protein Box', '18.04.2021', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (14, 'Cheese Trio Protein Box', '27.06.2021', false);
insert into food (food_id, variety, expiration_date, refridgerated) values (15, 'Cheddar & Uncured Salami Protein Box', '07.11.2021', false);
insert into food (food_id, variety, expiration_date, refridgerated) values (16, 'Chicken & Bacon on Brioche', '04.12.2021', false);
insert into food (food_id, variety, expiration_date, refridgerated) values (17, 'Protein Boxes', '31.01.2022', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (18, 'Chicken & Bacon on Brioche', '16.09.2021', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (19, 'Chicken Caprese on Ciabatta', '02.08.2021', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (20, 'Tomato & Mozzarella on Focaccia', '09.09.2021', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (21, 'Cheddar & Uncured Salami Protein Box', '20.03.2021', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (22, 'Ham & Swiss on Baguette', '13.09.2021', false);
insert into food (food_id, variety, expiration_date, refridgerated) values (23, 'Chicken & Bacon on Brioche', '15.06.2021', false);
insert into food (food_id, variety, expiration_date, refridgerated) values (24, 'Tomato & Mozzarella on Focaccia', '18.03.2021', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (25, 'Turkey, Provolone & Pesto on Ciabatta', '14.04.2021', false);
insert into food (food_id, variety, expiration_date, refridgerated) values (26, 'Cheese & Fruit Protein Box', '05.07.2021', false);
insert into food (food_id, variety, expiration_date, refridgerated) values (27, 'Chicken & Hummus Protein Box', '14.11.2021', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (28, 'Chickpea Bites & Avocado Protein Box', '18.04.2021', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (29, 'Tomato & Mozzarella on Focaccia', '08.01.2022', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (30, 'Chicken & Hummus Protein Box', '31.12.2021', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (31, 'Ham & Swiss on Baguette', '20.02.2022', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (32, 'Chicken Caprese on Ciabatta', '02.09.2021', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (33, 'Cheese & Fruit Protein Box', '09.01.2022', false);
insert into food (food_id, variety, expiration_date, refridgerated) values (34, 'Turkey, Provolone & Pesto on Ciabatta', '27.12.2021', false);
insert into food (food_id, variety, expiration_date, refridgerated) values (35, 'Tomato & Mozzarella on Focaccia', '06.03.2022', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (36, 'Avocado Spread', '13.11.2021', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (37, 'Tomato & Mozzarella on Focaccia', '29.08.2021', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (38, 'Cheese Trio Protein Box', '11.04.2021', false);
insert into food (food_id, variety, expiration_date, refridgerated) values (39, 'Protein Boxes', '14.06.2021', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (40, 'Chicken & Hummus Protein Box', '08.04.2021', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (41, 'Turkey, Provolone & Pesto on Ciabatta', '23.06.2021', false);
insert into food (food_id, variety, expiration_date, refridgerated) values (42, 'Chicken & Bacon on Brioche', '25.07.2021', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (43, 'Avocado Spread', '18.08.2021', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (44, 'Eggs & Cheddar Protein Box', '05.02.2022', true);
insert into food (food_id, variety, expiration_date, refridgerated) values (45, 'PB&J Protein Box', '10.10.2021', false);
insert into food (food_id, variety, expiration_date, refridgerated) values (46, 'Tomato & Mozzarella on Focaccia', '04.02.2022', false);
